#服务配置
server:
  #服务端口
  port: 8080
  servlet:
    # 项目contextPath
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 20
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 5

#Spring配置
spring:
  #thymeleaf配置，默认前缀为templates
  thymeleaf:
    mode: HTML
    encoding: utf-8
    # 禁用缓存
    cache: false

  datasource:
    #springboot2.02版本默认使用HikariCP
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.h2.Driver
    #url: jdbc:h2:tcp://localhost/D:/win/h2data/demo
    #通过使用TCP/IP的服务器模式,连接内存中的demo数据库,如果不存在数据库，会自动创建
    url: jdbc:h2:tcp://localhost/mem:demo
    username: test
    password: test
    validation-query: SELECT 1    
  devtools:
    restart:
      #热部署开关
      enabled: false
  #redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 60s
    #连接池配置，springboot2.x默认使用lettuce，也可以引入jedis
    lettuce:
      pool:
        #最大连接数，负数为不限制
        max-active: 20
        #最大等待可用连接的时间，负数为不限制
        max-wait: 10000ms
        #最大空闲连接数
        max-idle: 10
        #最小空闲连接数
        min-idle: 2
        
# MyBatis配置
mybatis:
    # 搜索指定包别名
  typeAliasesPackage: com.springboot2.test4
    # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath:mapper/*Mapper.xml
    # 加载全局的配置文件
  configLocation: classpath:property/mybatis-config.xml
