#服务配置
server:
  #服务端口
  port: 8080
  servlet:
    # 项目contextPath
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 20
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 5

#Spring配置
spring:
  #thymeleaf配置，默认前缀为templates
  thymeleaf:
    mode: HTML
    encoding: utf-8
    # 禁用缓存
    cache: false
  datasource:
    #springboot2.02版本默认使用HikariCP
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: q123
     # 初始连接数
    initial-size: 1
    # 最大连接数
    max-active: 10
    #最小空闲连接数   max-idle在druid中不使用了，配置了也不会生效
    min-idle: 1
    # 配置获取连接等待超时的时间(毫秒)
    max-wait: 10000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    min-evictable-idle-time-millis: 300000
    # 检验sql语句，以下3项，必需配置了validation-query才会生效
    # 查询结果必需有返回行
    validation-query: SELECT 1
    # 是否空闲连接回收器校验连接，不消耗性能，建议开启
    test-while-idle: true
    # 连接取出时是否校验，默认true，开启消耗性能，建议关闭
    test-on-borrow: false
    #连接放入时是否校验，开启消耗性能，建议关闭
    test-on-return: false
  devtools:
    restart:
      #热部署开关
      enabled: true
# MyBatis配置
mybatis:
    # 搜索指定包别名
  typeAliasesPackage: com.springboot2.test3
    # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath:mapper/*Mapper.xml
    # 加载全局的配置文件
  configLocation: classpath:property/mybatis-config.xml
