#服务配置
server:
  #服务端口
  port: 8080
  servlet:
    # 项目contextPath
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 20
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 5

#Spring配置
spring:
  #freemarker模板前缀，后缀配置
  freemarker:
    template-loader-path: classpath:/template/
    suffix: .html
  devtools:
    restart:
      #热部署开关
      enabled: true

